version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER=edvora_fastapi
      - POSTGRES_PASSWORD=edvora_fastapi
      - POSTGRES_DB=edvora_fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgres_data:
